projects:
  pronto:
    schemaPath: graphql/schema.graphql
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        version: 3
extensions:
  amplify:
    version: 3
