/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": process.env.REACT_APP_AWS_REGION,
  "aws_cloud_logic_custom": [
    {
      "name": process.env.REACT_APP_AWS_CLOUD_NAME,
      "endpoint": process.env.REACT_APP_AWS_ENDPOINT,
      "region": process.env.REACT_APP_AWS_REGION
    }
  ],
  "aws_appsync_graphqlEndpoint": process.env.REACT_APP_AWS_APPSYNC_ENDPOINT,
  "aws_appsync_region": process.env.REACT_APP_AWS_REGION,
  "aws_appsync_authenticationType": process.env.REACT_APP_SYNC_AUTHENTICATION_TYPE,
  "aws_appsync_apiKey": process.env.REACT_APP_APPSYNC_API_KEY,
  "aws_cognito_identity_pool_id": process.env.REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID,
  "aws_cognito_region": process.env.REACT_APP_AWS_REGION,
  "aws_user_pools_id": process.env.REACT_APP_AWS_USER_POOL_ID,
  "aws_user_pools_web_client_id": process.env.REACT_APP_WEB_CLIENT_ID,
  "oauth": {},
  "aws_cognito_username_attributes": [
    process.env.REACT_APP_AWS_COGNITO_USERNAME_ATTRIBUTES
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    process.env.REACT_APP_AWS_COGNITO_USERNAME_ATTRIBUTES,
    process.env.REACT_APP_AWS_COGNITO_SIGNUP_ATTRIBUTE_SURNAME,
    process.env.REACT_APP_AWS_COGNITO_SIGNUP_ATTRIBUTE_NAME
  ],
  "aws_cognito_mfa_configuration": process.env.REACT_APP_AWS_COGNITO_MFA_CONFIG,
  "aws_cognito_mfa_types": [
    process.env.REACT_APP_AWS_COGNITO_MFA_TYPES
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    process.env.REACT_APP_COGNITO_VERIFICATION_MECHANISMS
  ],
  "aws_user_files_s3_bucket": process.env.REACT_APP_AWS_USER_FILES_S3_BUCKET,
  "aws_user_files_s3_bucket_region": process.env.REACT_APP_AWS_REGION
};


export default awsmobile;
