/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://cawzwlq5ibemvp7wj76elkn63y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-ssdur63gp5aklg5gpvhwlosujm",
    "aws_cognito_identity_pool_id": "us-east-1:2c60cae9-c0bc-4674-84f5-468547489397",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LLMUI6foi",
    "aws_user_pools_web_client_id": "17valkv4rb6ifi4qte115ph4nu",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Analytics": {
        "AWSPinpoint": {
            "appId": "af6f9cf9dd6144f58bdf7dc9b9dc7672",
            "region": "us-east-1"
        }
    }
};


export default awsmobile;
