/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: process.env.REACT_APP_aws_project_region,
    aws_mobile_analytics_app_id: process.env.REACT_APP_aws_mobile_analytics_app_id,
    aws_mobile_analytics_app_region: process.env.REACT_APP_aws_mobile_analytics_app_region,
    Analytics: {
        AWSPinpoint: {
            appId: process.env.REACT_APP_aws_mobile_analytics_app_id,
            region: process.env.REACT_APP_aws_mobile_analytics_app_region,
        },
    },
    aws_cloud_logic_custom: [
        {
            name: "AdminQueries",
            endpoint: process.env.REACT_APP_AWS_CLOUD_LOGIC_CUSTOM_0_endpoint,
            region: process.env.REACT_APP_AWS_CLOUD_LOGIC_CUSTOM_0_region,
        },
    ],
    aws_appsync_graphqlEndpoint: process.env.REACT_APP_aws_appsync_graphqlEndpoint,
    aws_appsync_region: process.env.REACT_APP_aws_appsync_region,
    aws_appsync_authenticationType: process.env.REACT_APP_aws_appsync_authenticationType,
    aws_appsync_apiKey: process.env.REACT_APP_aws_appsync_apiKey,
    aws_cognito_identity_pool_id: process.env.REACT_APP_aws_cognito_identity_pool_id,
    aws_cognito_region: process.env.REACT_APP_aws_cognito_region,
    aws_user_pools_id: process.env.REACT_APP_aws_user_pools_id,
    aws_user_pools_web_client_id: process.env.REACT_APP_aws_user_pools_web_client_id,
    oauth: {},
    aws_cognito_username_attributes: [process.env.REACT_APP_aws_cognito_verification_mechanisms_0],
    aws_cognito_social_providers: [],
    aws_cognito_signup_attributes: [process.env.REACT_APP_aws_cognito_verification_mechanisms_0, process.env.REACT_APP_FAMILY_NAME, process.env.REACT_APP_GIVEN_NAME],
    aws_cognito_mfa_configuration: process.env.REACT_APP_aws_cognito_mfa_configuration,
    aws_cognito_mfa_types: [process.env.REACT_APP_aws_cognito_mfa_types_0],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: process.env.REACT_APP_aws_cognito_password_protection_settings_passwordPolicyMinLength,
        passwordPolicyCharacters: [
            process.env.REACT_APP_aws_cognito_password_protection_settings_passwordPolicyCharacters_0,
            process.env.REACT_APP_aws_cognito_password_protection_settings_passwordPolicyCharacters_1,
            process.env.REACT_APP_aws_cognito_password_protection_settings_passwordPolicyCharacters_2,
            process.env.REACT_APP_aws_cognito_password_protection_settings_passwordPolicyCharacters_3,
        ],
    },
    aws_cognito_verification_mechanisms: [process.env.REACT_APP_aws_cognito_verification_mechanisms_0],
    aws_user_files_s3_bucket: process.env.REACT_APP_aws_user_files_s3_bucket,
    aws_user_files_s3_bucket_region: process.env.REACT_APP_aws_user_files_s3_bucket_region,
};

export default awsmobile;
