process.env.COGNITO_MOBILE_CLIENT_ID = "APP_CLIENTID";
process.env.COGNITO_WEB_CLIENT_ID = "WEB_CLIENTID";
process.env.STUDENT_GROUP_NAME = "STUDENTSGROUPNAME";
process.env.LECTURER_GROUP_NAME = "LECTURERGROUPNAME";
process.env.ADMIN_GROUP_NAME = "ADMINGROUPNAME";
process.env.MODULES = "add-to-group,add-institution-attribute";
process.env.API_API_PRONTO_GRAPHQLAPIENDPOINT =
  "API_API_PRONTO_GRAPHQLAPIENDPOINTOUTPUT";
process.env.API_API_PRONTO_GRAPHQLAPIKEY = "API_API_PRONTO_GRAPHQLAPIKEYOUTPUT";
