/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://yzey2x5bt5drzn5nw5tubvm4dm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-as6pdd7lm5hgpmebnignkpec2u",
    "aws_cognito_identity_pool_id": "us-east-1:24b44a78-0b95-4be6-bdc7-14d043e0f222",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_OZ7d8w67I",
    "aws_user_pools_web_client_id": "3uqlt9r8vsml0g02noh7v87dno",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "ADDRESS",
        "EMAIL",
        "FAMILY_NAME",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "pronto-blobe-store153713-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
