process.env.COGNITO_MOBILE_CLIENT_ID = "APP_CLIENTID";
process.env.COGNITO_WEB_CLIENT_ID = "WEB_CLIENTID";
process.env.StudentsGroupName = "STUDENTSGROUPNAME";
process.env.LecturersGroupName = "LECTURERGROUPNAME";
process.env.AdminGroupName = "ADMINGROUPNAME";
process.env.MODULES = "add-to-group";
process.env.API_API_PRONTO_GRAPHQLAPIENDPOINTOUTPUT =
  "API_API_PRONTO_GRAPHQLAPIENDPOINTOUTPUT";
process.env.API_API_PRONTO_GRAPHQLAPIKEYOUTPUT =
  "API_API_PRONTO_GRAPHQLAPIKEYOUTPUT";
