name: Backend Unit Tests
on:
  push:
    branches: [main, dev, restoreBackend,  backend, pre-main]
  pull_request:
    branches: [main, dev, frontend, pre-main, backend]

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: ./amplify/backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: |
          cd function/prontoAuthPostConfirmation/src
          npm install
          cd ../../prontoAuthPreAuthentication/src
          npm install
          cd ../../prontoAuthPreSignup/src
          npm install
          cd ../../../
          npm test
