name: Build-backend
on: 
  pull_request:
    branches: [backend,main]
  workflow_dispatch: {}     

jobs: 
  build:
    runs_on: ubuntu-latest
    with: 
      node-version: '16'
    steps:
      steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      -name: setup 
        run: |
          npm install -g @aws-amplify/cli
          amplify init -y
      -name: build 
        run: |        
          amplify serve
