name: Build Amplify
on:
  pull_request:
    branches: [ back-end,main,dev ] 
  push: 
    branches: [build/fix]    
  workflow_dispatch:   
jobs:
  build:
    strategy:
      matrix:
        node_version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # We need to AWS CLI to configure the account and profile credentials.
      # Note: The --profile {default} needs to be the same that the profileName in the init.sh
      - name: Install AWS CLI 
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -u awscliv2.zip
          sudo ./aws/install --update

      - name: Configure credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          APP_ID: ${{secrets.APP_ID}}
        run: |    
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
          aws configure set default.region us-east-1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}

      - name: Install Amplify CLI & Building Project
        run: |     
          npm install -g @aws-amplify/cli 
          bash scripts/configure-amplify.sh
          # amplify pull --yes
          # amplify build