name: Build-backend
on: 
  pull_request:
    branches: [backend,dev,main]
  workflow_dispatch: {}     

jobs: 
  build:
    runs_on: windows-latest
    steps:
      -name: setup 
        run:
            npm install -g @aws-amplify/cli
            amplify init -y
      -name: build          
      amplify serve
