# name: Lint Code Base
# on:
#   push:
#     branches-ignore: [main,dev,back-end,front-end]
#   pull_request:
#     branches: [main,dev,back-end,front-end]
#   workflow_dispatch: {}  

# jobs:
#   Fomrat:
#     build: 
#       runs-on:  ubuntu-latest
    
#      strategy:
#         matrix:
#           node-version: [ 18.x]

#       steps: 
#         - uses: actions/checkout@v3
#         - name: Use Node.js ${{ matrix.node-version }}
#           uses: actions/setup-node@v3
#           with:
#             node-version: ${{ matrix.node-version }}
#             cache: 'npm'
#         - run: | 
#             npm install standard --global
#             standard --fix

#   Lint:
#     needs: Fomrat
#     build:
  
#       runs-on: ubuntu-latest

#       permissions:
#         contents: write
#         packages: write
#         statuses: write

#       steps:
#         - name: Checkout Code
#           uses: actions/checkout@v3
#           with:
#             fetch-depth: 0
          
#         - name: Lint Code Base
#           uses: github/super-linter@v5
#           env:
#             VALIDATE_ALL_CODEBASE: false
#             IGNORE_GENERATED_FILES: true
#             IGNORE_GITIGNORED_FILES: true
#             DEFAULT_BRANCH: main
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Lint Code bas

on:
  push:
    branches-ignore: [main, dev]
  pull_request:
    branches: [main, dev, Automated-Testing]

jobs:
  format:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: |
          npm install standard --global
          standard --fix

  lint:
    need: format
    runs-on: ubuntu-latest

      permissions:
        contents: write
        packages: write
        statuses: write

      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
          
        - name: Lint Code Base
          uses: github/super-linter@v5
          env:
            VALIDATE_ALL_CODEBASE: false
            IGNORE_GENERATED_FILES: true
            IGNORE_GITIGNORED_FILES: true
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
