name: Lint Code Base


on:
  push:
    branches-ignore: [main,dev,back-end,front-end]
  pull_request:
    branches: [main,dev,back-end,front-end]
  workflow_dispatch: {}  

jobs:
  build:
    
    name: Lint Code Base
    
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: false
          IGNORE_GITIGNORED_FILES: true
          IGNORE_GENERATED_FILES: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}