name: Unit and Integration Tests

on:
  push:
    branches: [ main, dev, integration, backend ]
  pull_request:
    branches: [ main, dev, integration, backend ]

jobs:
  build-mobile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: ./MobileApp
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --u

  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: "Web view/Web app"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: |
          npm ci
          npm run build --if-present
          npm test

  build-backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: "amplify/backend"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: |
          npm ci
          npm test

  cypress-tests-web-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Web view/Web app"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start


