name: Unit and Integration Tests

on:
  push:
    branches: [main, dev, integration, backend]
  pull_request:
    branches: [main, dev, integration, backend]

jobs:

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run React app and Cypress e2e tests
        run: npx start-server-and-test start http://localhost:3000 cypress:run
