name: Unit and Integration Tests

on:
  push:
    branches: [ main, dev, integration, backend ]
  pull_request:
    branches: [ main, dev, integration, backend ]

jobs:
  
  cypress-tests-web-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Web view/Web app"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install node modules
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm start



