name: Build Mobile App with Amplify Backend

on:
  push:
    branches: [main, dev, frontend, integration, Pipeline-Set-Up]
  pull_request:
    branches: [main, dev, frontend, integration, Pipeline-Set-Up]

jobs:
  build-mobile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    defaults:
      run:
        working-directory: ./MobileApp

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: npm run build --if-present
      - run: npm test -- --coverage


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: --branch=Pipeline-Set-Up
          directory: ./MobileApp


#  build-backend:
 #       runs-on: ubuntu-latest
#        strategy:
#          matrix:
#            node-version: [ 18.x ]
#        defaults:
#          run:
#            working-directory: "./amplify/backend"

#        steps:
#          - uses: actions/checkout@v3
#          - name: Use Node.js ${{ matrix.node-version }}
#            uses: actions/setup-node@v3
#            with:
#              node-version: ${{ matrix.node-version }}
#         - run: |
#               npm install
#              npm test 
#
#          - name: Install Amplify CLI and Build Backend
#            run: |
#              npm install -g @aws-amplify/cli
#              amplify configure
#              amplify init --appId ${{ secrets.APP_ID }} 
#              amplify build

  build-web:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 18.x ]
      defaults:
        run:
          working-directory: ./WebApp
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version}}
        - run: |
            npm install
            npm test

  build-amplify:
   runs-on: ubuntu-latest
   strategy:
     matrix:
      node_version: [12.x]
 
   steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install Amplify CLI
      run: npm install -g @aws-amplify/cli

    - name: Configure AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    - name: Initialize Amplify
      run: bash scripts/initialize-amplify.sh

    - name: Build Amplify Project
      run: amplify build


 # cypress:
 #   runs-on: ubuntu-latest
 #   strategy:
 #     matrix:
 #       node-version: [ 18.x ]
 #   defaults:
 #     run:
 #       working-directory: ./WebApp
 #   steps:
 #     - name: Checkout
 #       uses: actions/checkout@v2
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: 14

#      - name: Install dependencies
#        run: npm install

 #     - name: Build and start the app
 #       run: |
  #        npm start &
 #         sleep 30

  #   - name: Run Cypress tests
   #     run: npx cypress run

