name: Build status

on:
  push:
    branches: [ "frontend-dev" ]
  pull_request:
    branches: [ "frontend-dev" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18.x]
        # Version 18 has been used : Node.js 18 LTS

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present



