name: Pronto

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-mobile:
   strategy:
      matrix:
        node-version: [ 18.x]
    defaults:
      run:
        working-directory: ./MobileApp

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci 
      - run: npm run build --if-present
      - run: npm test

    build-web:
      strategy:
        matrix: 
          node-version: [18.x]
      defaults:
        run:
          working-directory: ./WebView/WebApp
      steps: 
        -uses: actions/checkout@v3
        -name: Use Node.js ${{matrix.node-version}}
         uses: actions/setup-node@v3
         with:
            node-version: ${{ matrix.node-version}} 
        - run: | 
            npm ci
            npm run build --if-present
            npm test  



