name: Unit and Integration Tests

on:
  push:
    branches: [ main, dev, integration, backend ]
  pull_request:
    branches: [ main, dev, integration, backend ]

jobs:
  
  cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Web view/Web app"  # Replace this with the actual path to your React app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      
      - name: Install dependencies and run Cypress tests
        run: |
          npm ci
          npx cypress run



