name: Build Mobile,Web App and Amplify Backend

on:
  push:
    branches: [ main, dev, frontend, integration, backend, fix---auth ]
  pull_request:
    branches: [ main, dev, frontend, integration, backend, fix---auth ]

jobs:
  build-mobile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: ./MobileApp
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: --branch=Pipeline-Set-Up
          directory: ./MobileApp

  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: ./WebApp
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}}
      - run: |
          npm install
          npm test

  build-backend:
    strategy:
      matrix:
        node_version: [ 12.x ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -u awscliv2.zip
          sudo ./aws/install --update
      - name: Configure credentials
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile default
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile default
          aws configure set default.region us-east-1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: amplify

      - name: Install Amplify CLI & Building Project
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        run: |
          npm install -g @aws-amplify/cli 
          bash scripts/initialise-amplify.sh
          amplify build

  cypress-run:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set working directory and install dependencies
      run: |
        cd ./WebApp   
        npm install
      env:
        LECTURER_PASSWORD: ${{ secrets.LECTURER_PASSWORD }}   # Retrieve secret value and set as an environment variable

    - name: Test
      run: |
        echo "Secret Value: $LECTURER_PASSWORD"  # Print the secret value
        export CYPRESS_LECTURER_PASSWORD="$LECTURER_PASSWORD"
        echo "Cypress Environment Variable: $CYPRESS_LECTURER_PASSWORD"

    - name: Run Cypress tests
      run: |
        cd ./WebApp  
        npx cypress run
